// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlCNiRGZo7eKfxEYzL_1gJiFn53QQcrcU',
    appId: '1:915174998370:web:f700ca496a30b3ca632c3b',
    messagingSenderId: '915174998370',
    projectId: 'bikerent-5946d',
    authDomain: 'bikerent-5946d.firebaseapp.com',
    storageBucket: 'bikerent-5946d.firebasestorage.app',
    measurementId: 'G-QMXWCNR8PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATbcdaUtLMAFriPMmQCb1jnAug-irWhDM',
    appId: '1:915174998370:android:830a47db5d00b314632c3b',
    messagingSenderId: '915174998370',
    projectId: 'bikerent-5946d',
    storageBucket: 'bikerent-5946d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmDoUq4nFx-JCk_jhkDQIbEn6aI49ib0c',
    appId: '1:915174998370:ios:ff8521a81c0a3400632c3b',
    messagingSenderId: '915174998370',
    projectId: 'bikerent-5946d',
    storageBucket: 'bikerent-5946d.firebasestorage.app',
    iosBundleId: 'com.example.bikerental',
  );
}
